In [2]:
import numpy as np
from sklearn import datasets
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import LinearSVC

In [3]:
iris = datasets.load_iris()

In [4]:
X = iris['data'][:,(2,3)]
y = (iris['target'] == 2).astype(np.float64)

In [5]:
svm_clf = Pipeline([
    ('scalar', StandardScaler()),
    ('linear_svc', LinearSVC(C=1, loss='hinge'))
])

In [6]:
svm_clf.fit(X,y)

Pipeline(steps=[('scalar', StandardScaler()),
                ('linear_svc', LinearSVC(C=1, loss='hinge'))])

In [7]:
svm_clf.predict([[5.5, 1.7]])

array([1.])

In [8]:
from sklearn.datasets import make_moons
from sklearn.preprocessing import PolynomialFeatures

In [9]:
X, y = make_moons(n_samples=100, noise=0.15)

In [10]:
polynomial_svm_clf = Pipeline([
    ('poly_features', PolynomialFeatures(degree=3)),
    ('scaler', StandardScaler()),
    ('svm_clf', LinearSVC(C=10, loss='hinge', max_iter=100000))
])

In [11]:
polynomial_svm_clf.fit(X,y)

Pipeline(steps=[('poly_features', PolynomialFeatures(degree=3)),
                ('scaler', StandardScaler()),
                ('svm_clf', LinearSVC(C=10, loss='hinge', max_iter=100000))])

In [12]:
from sklearn.model_selection import cross_val_score

In [13]:
from sklearn.svm import SVC

In [14]:
poly_kernel_svm_clf = Pipeline([
    ('scaler', StandardScaler()),
    ('svm_clf', SVC(kernel='poly', degree=4,coef0=1, C=5))
])
cross_val_score(poly_kernel_svm_clf, X, y, cv=5, scoring='accuracy').mean()

1.0

In [15]:
rbf_kernel_svm_clf = Pipeline([
    ('scalar', StandardScaler()),
    ('svm_clf', SVC(kernel='rbf', gamma=4.8, C=0.001))
])
cross_val_score(rbf_kernel_svm_clf, X, y, cv=5, scoring='accuracy').mean()

0.97

In [16]:
from sklearn.svm import LinearSVR

In [25]:
from sklearn.linear_model import SGDClassifier

In [26]:
?SGDClassifier

In [17]:
svm_reg = LinearSVR(epsilon=1.5)

In [138]:
polynomial_svm_linear = Pipeline([
    ('scaler', StandardScaler()),
    ('svm_clf', LinearSVC(C=10, loss='hinge', max_iter=100000))
])
polynomial_svm_svc = Pipeline([
    ('scaler', StandardScaler()),
    ('svm_clf', SVC(C=10, kernel='linear',max_iter=100000))
])

polynomial_svm_sgd = Pipeline([
    ('scaler', StandardScaler()),
    ('svm_clf', SGDClassifier(alpha=1/(10*len(X)), loss='hinge', max_iter=100000, tol=1e-5))
])

In [51]:
cross_val_score(polynomial_svm_linear, X, y, cv=5, scoring='accuracy')

array([0.85, 0.95, 0.8 , 0.9 , 0.9 ])

In [134]:
polynomial_svm_linear.fit(X, y)
polynomial_svm_linear[-1].intercept_, polynomial_svm_linear[-1].coef_

(array([-0.04692283]), array([[ 0.76395356, -1.56688527]]))

In [139]:
polynomial_svm_sgd.fit(X, y)
polynomial_svm_sgd[-1].intercept_, polynomial_svm_sgd[-1].coef_

(array([-0.40824405]), array([[ 1.71948664, -1.68154347]]))

In [137]:
polynomial_svm_svc.fit(X, y)
polynomial_svm_svc[-1].intercept_, polynomial_svm_svc[-1].coef_

(array([-0.04691288]), array([[ 0.76393143, -1.5669506 ]]))